// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G1ACmgIQc4igYLveDuYaiFq4wBuVDmw',
    appId: '1:698637353524:web:4b0e3d4ebacb839c9b8061',
    messagingSenderId: '698637353524',
    projectId: 'tutorpro-fef8f',
    authDomain: 'tutorpro-fef8f.firebaseapp.com',
    storageBucket: 'tutorpro-fef8f.appspot.com',
    measurementId: 'G-KJH47V6DKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU-a_fohvGhi4Yc053749XyJ1_S7D0aag',
    appId: '1:698637353524:android:1410a743c2a715b79b8061',
    messagingSenderId: '698637353524',
    projectId: 'tutorpro-fef8f',
    storageBucket: 'tutorpro-fef8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJIv7gsJfKad8zY93bikjpndcNLxkQC4',
    appId: '1:698637353524:ios:e225065dc68136f39b8061',
    messagingSenderId: '698637353524',
    projectId: 'tutorpro-fef8f',
    storageBucket: 'tutorpro-fef8f.appspot.com',
    iosBundleId: 'com.example.tutorpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJIv7gsJfKad8zY93bikjpndcNLxkQC4',
    appId: '1:698637353524:ios:e225065dc68136f39b8061',
    messagingSenderId: '698637353524',
    projectId: 'tutorpro-fef8f',
    storageBucket: 'tutorpro-fef8f.appspot.com',
    iosBundleId: 'com.example.tutorpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0G1ACmgIQc4igYLveDuYaiFq4wBuVDmw',
    appId: '1:698637353524:web:d2c5d26aa510c1ec9b8061',
    messagingSenderId: '698637353524',
    projectId: 'tutorpro-fef8f',
    authDomain: 'tutorpro-fef8f.firebaseapp.com',
    storageBucket: 'tutorpro-fef8f.appspot.com',
    measurementId: 'G-1HHEKFHYCM',
  );
}
